"""
Crappy handmade list to get all the items from the bit shop since the API doesnt do that
Copyright (C) 2024 Romayne (Contact @ https://github.com/MyNameIsRomayne)
"""

bit_items = {
    "God Potion":{
        "item_id": "GOD_POTION_2",
        "product_id": None,
        "cost_bits": 1500,
        "cost_coins": 0,
    },
    "Kismet Feather":{
        "item_id": "KISMET_FEATHER",
        "product_id": "KISMET_FEATHER",
        "cost_bits": 1350,
        "cost_coins": 0,
    },
    "Kat Flower":{
        "item_id": "KAT_FLOWER",
        "product_id": None,
        "cost_bits": 500,
        "cost_coins": 0,
    },
    "Kat Bouquet":{
        "item_id": "KAT_BOUQUET",
        "product_id": None,
        "cost_bits": 2500,
        "cost_coins": 0,
    },
    "Matriarch's Perfume":{
        "item_id": "MATRIARCH_PARFUM",
        "product_id": None,
        "cost_bits": 1200,
        "cost_coins": 0,
    },
    "Hologram":{
        "item_id": "HOLOGRAM",
        "product_id": None,
        "cost_bits": 2000,
        "cost_coins": 0,
    },
    "Ditto Blob":{
        "item_id": "DITTO_BLOB",
        "product_id": None,
        "cost_bits": 600,
        "cost_coins": 0,
    },
    "Builder's Wand":{
        "item_id": "BUILDERS_WAND",
        "product_id": None,
        "cost_bits": 12000,
        "cost_coins": 0,
    },
    "Block Zapper":{
        "item_id": "BLOCK_ZAPPER",
        "product_id": None,
        "cost_bits": 5000,
        "cost_coins": 0,
    },
    "Bits Talisman":{
        "item_id": "BITS_TALISMAN",
        "product_id": None,
        "cost_bits": 15000,
        "cost_coins": 0,
    },
    "Portalizer":{
        "item_id": "PORTALIZER",
        "product_id": None,
        "cost_bits": 4800,
        "cost_coins": 0,
    },
    "Autopet Rules 2-Pack":{
        "item_id": "AUTOPET_RULES_2",
        "product_id": None,
        "cost_bits": 21000,
        "cost_coins": 0,
    },
    "Inferno Fuel Block":{
        "item_id": "INFERNO_FUEL_BLOCK",
        "product_id": "INFERNO_FUEL_BLOCK",
        "cost_bits": 75,
        "cost_coins": 0,
    },
    "Heat Core":{
        "item_id": "HEAT_CORE",
        "product_id": None,
        "cost_bits": 3000,
        "cost_coins": 0,
    },
    "Hyper Catalyst Upgrade":{
        "item_id": "HYPER_CATALYST_UPGRADE",
        "product_id": "HYPER_CATALYST",
        "cost_bits": 300,
        "cost_coins": 0,
    },
    "Ultimate Carrot Candy Upgrade":{
        "item_id": "ULTIMATE_CARROT_CANDY_UPGRADE",
        "product_id": None,
        "cost_bits": 8000,
        "cost_coins": 0,
    },
    "Colossal Experience Bottle Upgrade":{
        "item_id": "COLOSSAL_EXP_BOTTLE_UPGRADE",
        "product_id": None,
        "cost_bits": 1200,
        "cost_coins": 0,
    },
    "Jumbo Backpack Upgrade":{
        "item_id": "JUMBO_BACKPACK_UPGRADE",
        "product_id": None,
        "cost_bits": 4000,
        "cost_coins": 0,
    },
    "Minion Storage X-pender":{
        "item_id": "MINION_STORAGE_EXPANDER",
        "product_id": None,
        "cost_bits": 1500,
        "cost_coins": 0,
    },
    "Expertise I":{
        "item_id": "None",
        "product_id": "ENCHANTMENT_EXPERTISE_1",
        "cost_bits": 4000,
        "cost_coins": 0,
    },
    "Compact I":{
        "item_id": "None",
        "product_id": "ENCHANTMENT_COMPACT_1",
        "cost_bits": 4000,
        "cost_coins": 0,
    },
    "Cultivating I":{
        "item_id": "None",
        "product_id": "ENCHANTMENT_CULTIVATING_1",
        "cost_bits": 4000,
        "cost_coins": 0,
    },
    "Champion I":{
        "item_id": "None",
        "product_id": "ENCHANTMENT_CHAMPION_1",
        "cost_bits": 4000,
        "cost_coins": 0,
    },
    "Hecatomb I":{
        "item_id": "None",
        "product_id": "ENCHANTMENT_HECATOMB_1",
        "cost_bits": 6000,
        "cost_coins": 0,
    },
    "Toxophilite I":{
        "item_id": "None",
        "product_id": "ENCHANTMENT_TOXOPHILITE_1",
        "cost_bits": 4000,
        "cost_coins": 0,
    },
    "Speed Enrichment":{
        "item_id": "TALISMAN_ENRICHMENT_WALK_SPEED",
        "product_id": None,
        "cost_bits": 5000,
        "cost_coins": 0,
    },
    "Intelligence Enrichment":{
        "item_id": "TALISMAN_ENRICHMENT_INTELLIGENCE",
        "product_id": None,
        "cost_bits": 5000,
        "cost_coins": 0,
    },
    "Critical Damage Enrichment":{
        "item_id": "TALISMAN_ENRICHMENT_CRITICAL_DAMAGE",
        "product_id": None,
        "cost_bits": 5000,
        "cost_coins": 0,
    },
    "Critical Chance Enrichment":{
        "item_id": "TALISMAN_ENRICHMENT_CRITICAL_CHANCE",
        "product_id": None,
        "cost_bits": 5000,
        "cost_coins": 0,
    },
    "Strength Enrichment":{
        "item_id": "TALISMAN_ENRICHMENT_STRENGTH",
        "product_id": None,
        "cost_bits": 5000,
        "cost_coins": 0,
    },
    "Defense Enrichment":{
        "item_id": "TALISMAN_ENRICHMENT_DEFENSE",
        "product_id": None,
        "cost_bits": 5000,
        "cost_coins": 0,
    },
    "Health Enrichment":{
        "item_id": "TALISMAN_ENRICHMENT_HEALTH",
        "product_id": None,
        "cost_bits": 5000,
        "cost_coins": 0,
    },
    "Magic Find Enrichment":{
        "item_id": "TALISMAN_ENRICHMENT_MAGIC_FIND",
        "product_id": None,
        "cost_bits": 5000,
        "cost_coins": 0,
    },
    "Ferocity Enrichment":{
        "item_id": "TALISMAN_ENRICHMENT_FEROCITY",
        "product_id": None,
        "cost_bits": 5000,
        "cost_coins": 0,
    },
    "Sea Creature Chance Enrichment":{
        "item_id": "TALISMAN_ENRICHMENT_SEA_CREATURE_CHANCE",
        "product_id": None,
        "cost_bits": 5000,
        "cost_coins": 0,
    },
    "Attack Speed Enrichment":{
        "item_id": "TALISMAN_ENRICHMENT_ATTACK_SPEED",
        "product_id": None,
        "cost_bits": 5000,
        "cost_coins": 0,
    },
    "Accessory Enrichment Swapper":{
        "item_id": "TALISMAN_ENRICHMENT_SWAPPER",
        "product_id": None,
        "cost_bits": 200,
        "cost_coins": 0,
    },
}